#!/usr/bin/env bash
# This script installs and configures Nginx to serve a "Hello World!" page

# Update the package list
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Create a custom index.html file with "Hello World!" message
echo "Hello World!" | sudo tee /var/www/html/index.html

# Restart Nginx
sudo service nginx restart

