#!/usr/bin/env bash
# This script installs and configures Nginx to serve a "Hello World!" page

# Update the package list and install nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

# Create a custom index.html file with "Hello World!" message
echo "Hello World!" > /var/www/html/index.html

# Restart nginx
service nginx restart

