#!/usr/bin/env bash
# Configure Nginx server to:
# - Display "Hello World!" at the root URL
# - Redirect /redirect_me to another URL with a 301 status code

# Update and upgrade the package lists
apt-get update -y && apt-get upgrade -y
apt-get install nginx -y
chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
line="\\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sed -i "48i $line" /etc/nginx/sites-available/default
service nginx restart

