#!/usr/bin/env bash
# Script to terminate the '7-highlander' process

# Find the PID of the '7-highlander' script
pid=$(pgrep -f '7-highlander')

# Check if the PID was found and kill the process
if [ -n "$pid" ]; then
    echo "Terminating '7-highlander' with PID $pid"
    kill -9 $pid
else
    echo "Process not found."
fi

